### ISSUE TITLE
The IsDefault switch on Add-SPOSiteDesign does not work

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-site-scripts#14]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
As documented [here](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/customize-default-site-design), it should be possible to add site scripts to a `default` site design (team site/communication site) by providing the `IsDefault` switch to the `Add-SPOSiteDesign` command.

#### Observed Behavior
No matter how I try to use the **Add-SPOSiteDesign** command with the `IsDefault` switch, a new site design always appears in the UI instead of being applied to the default site design. When clicking on the `+Create site` button in the UI and then on the `Team Site` tile,  I get a dropdown asking me to choose a design between **Team Site** and whatever the design I just created 

#### Steps to Reproduce
- Make sure you have a site script in a $script variable
- Run the following command
  ```powershell
  Add-SPOSiteDesign -Title "Default" -Description "Default" -WebTemplate "64" -SiteScripts $script -IsDefault
  ```
- Go in the UI and see that the Team Site definition has not changed, a new one has been created instead.

My **SharePoint Online Management Shell** is currently at version **16.0.7813.1200** (although the PowerShell module does display 16.0.7813.0)

**Comment by spplante** [comment]
After some further testing, it turns out that the site script DOES work on the out of the box `Team Site` site design. The issue seems like a display issue that makes the site design appear in the dropdown even if it has it's `IsDefault` property flagged to true.

I am pretty confident that this is not a normal behavior, I don't see why `Add-SPOSiteDesign` applied with the `IsDefault` switch should make available a NEW site design choice through the UI.

**Comment by spplante** [comment]
Moved to https://github.com/SharePoint/sp-dev-docs/issues/2236

**Comment by pdl5p** [comment]
This also happens when registering site designs using the rest api.
